---
  - hosts: all
    remote_user: ubuntu
    become: true
    tasks:
      - name: Trying to Install apache
        apt:
          name: httpd
          state: present
      - name: Trying to Install PHP
        apt:
          name: php5
          state: present
      - name: Goona start Apache service
        service:    
          name: httpd
          state: started
...